### ISSUE TITLE
<type> is not a supported composite type.

### ISSUE THREAD

**Issue by MrMika96** [georgebv/drf-pydantic#22]
Hello, i have encountered some strange behavior while trying to use .drf_serializer() method. I have BaseModel what looks like this
```
class ExampleDTO(BaseModel):
    field_1: Optional[Annotated[int, Field(description="Field1")]] = None
    field_2: Optional[Annotated[int, Field(description="Field2")]] = None
    field_3: Optional[Annotated[str, Field(description="Field3")]] = None
```
and this return me next error message:
```
drf_pydantic.errors.ModelConversionError: Error when converting model: ExampleDTO
field_1
     int is not a supported composite type.
field_2
     int is not a supported composite type.
field_3
     str is not a supported composite type.
```
     
Can you please suggest some solution?

**Comment by georgebv** [comment]
You are specifying types in the wrong order - `Annotated` must always come first. In your case it should be `Annotated[Optional[int], Field(...)]`

**Comment by MrMika96** [comment]
Thank you for a quick answer, the error message is gone! But "description" in Field is not displayed, description in my case is necessary because I use .drf_serializer() method to pass serializer to "parameters" in drf_spectacular extended_schema decorator. Can you please help with this too?

**Comment by georgebv** [comment]
@MrMika96 can you provide an example of what you are looking for? I need two models: one is for pydantic and another one is for drf serializer you'd expect it to generate. There is no `description` field in DRF https://www.django-rest-framework.org/api-guide/fields/

**Comment by georgebv** [comment]
Also keep in mind that you can specify drf serialier fields yourself: https://github.com/georgebv/drf-pydantic?tab=readme-ov-file#manual-serializer-configuration
