### ISSUE TITLE
Dict as JSONField

### ISSUE THREAD

**Issue by ragecryx** [georgebv/drf-pydantic#29]
I have a pydantic model that has a `dict` field which I usually mapped to a DRF `JSONField` but instead I get this error
`dict is not a supported scalar type.`.

How come this mapping between dict and [JSONField](https://www.django-rest-framework.org/api-guide/fields/#jsonfield) is not supported?
**Edit**: ...or even a [DictField](https://www.django-rest-framework.org/api-guide/fields/#dictfield) but that would assume ability to detect the `child` attribute, while JSONField would allow anything that's compatible with JSON primitives 🤔

**Comment by georgebv** [comment]
@ragecryx Can you provide a code sample to reproduce this error?

**Comment by ragecryx** [comment]
Yes, if you copy paste the following code in an interactive python terminal (assuming `drf_pydantic` is installed):
```python
from datetime import datetime
from drf_pydantic import BaseModel as DRFBaseModel

class AvailabilityRequest(DRFBaseModel):
    start_time: datetime
    end_time: datetime
    poi: dict
```
produces the error/exception I mentioned.

My intention is to accept [geojson](https://geojson.org/) in the `poi` field. I have done it in the past with JSONField in DRF serializers but in this case my `AvailabilityRequest` is not corresponding to a DB model so I cant use a DRF `ModelSerializer` and plain DRF `Serializer` doesnt help either because I want to pass around the `AvailabilityRequest` instance to various functions that do the actual work.

**Comment by georgebv** [comment]
@ragecryx I found the issue - I didn't expect that generic composite types like `list` or `dict` would be provided without annotation (e.g., `list[int]` or `dict[str, float]`). Your example should now work with the latest version https://github.com/georgebv/drf-pydantic/releases/tag/v2.5.1
