### ISSUE TITLE
Support python 3.7

### ISSUE THREAD

**Issue by manycoding** [georgebv/drf-pydantic#4]
Would be nice to have it. I tried to convert it myself, stuck on `types.GenericAlias` and  AttributeError: '_SpecialForm' object has no attribute '__origin__'

**Comment by georgebv** [comment]
This would require significant changes due to [PEP 585](https://peps.python.org/pep-0585/). The issue is with generics such as `typing.List[int]` (old) vs `list[int]` (new).
