### ISSUE TITLE
AssertionError for list fields

### ISSUE THREAD

**Issue by federicoparroni** [georgebv/drf-pydantic#6]
I'm getting the following error when I have schemas with List fields:

```python
from typing import List
from drf_pydantic import BaseModel

class Item(BaseModel):
    type: str
    quantity: int
    is_new: bool

class CartSchema(BaseModel):
    items: List[Item]
 
CartSchema.drf_serializer
```
This raise the AssertionError at:
https://github.com/georgebv/drf-pydantic/blob/01010e2e97f4cc1df0db94e1ad1b43482395b659/src/drf_pydantic/parse.py#L128

**Comment by georgebv** [comment]
Thank you for pointing this out, I see why this is happening. I'll fix it in the next update.

In the meantime you should use `list[Item]` instead of `List[Item]`. This is how this should be done in modern Python anyway (not saying that older typing shouldn't work).

**Comment by federicoparroni** [comment]
Thank you so much!
