### ISSUE TITLE
Collaborate with `django-pydantic-field`?

### ISSUE THREAD

**Issue by johnthagen** [georgebv/drf-pydantic#9]
This project seems to have a similar goal to `drf-pydantic`:

- https://github.com/surenkov/django-pydantic-field

Perhaps the two projects could work together so that the community can use a single package with the best of both projects?

**Comment by georgebv** [comment]
I am not sure I understand what that library does. Could you explain what's the use case in common words and what you think the overlap would be?

**Comment by johnthagen** [comment]
It looks like at it's core it's about annotating the shape/schema of `JSONField`s:

```py
from django_pydantic_field import SchemaField


class Foo(pydantic.BaseModel):
    count: int
    size: float = 1.0


class MyModel(models.Model):
    # Infer schema from field annotation
    foo_field: Foo = SchemaField()
```

So, it looks like it would be orthogonal/additional to this library. Integration could be that they play nicely together if you nest a `SchemaField` inside a `drf_pydantic.BaseModel`.

Was doing a survey of Django/Pydantic related fields and came across both this and the other library. I don't think there is anything actionable here, so I'll close the issue.
